spring.application.name=aluguelCarros
server.port=${PORT:8080}

## MySQL Configs
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/aluguel_carros?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:adm_carros}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:@GerenciaCarros123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## JPA Configs
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


